// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/spf13/cobra"
	"github.com/tomato-net/vault-agent/cli"
	"github.com/tomato-net/vault-agent/config"
	"github.com/tomato-net/vault-agent/logger"
	"github.com/tomato-net/vault-agent/renewer"
)

// Injectors from wire.go:

func ProvideCLI() (*cobra.Command, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	logrLogger := logger.New()
	renewerRenewer, err := renewer.New(configConfig, logrLogger)
	if err != nil {
		return nil, err
	}
	command := cli.New(renewerRenewer, logrLogger)
	return command, nil
}
