// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/spf13/cobra"
	"github.com/tomato-net/vault-agent/cli"
	"github.com/tomato-net/vault-agent/config"
	"github.com/tomato-net/vault-agent/logger"
	"github.com/tomato-net/vault-agent/token"
)

// Injectors from wire.go:

func ProvideCLI() (*cobra.Command, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	client, err := token.NewClient(configConfig)
	if err != nil {
		return nil, err
	}
	logrLogger := logger.New()
	providerLDAP := token.NewProviderLDAP(client, logrLogger, configConfig)
	renewer := token.NewRenewer(client, logrLogger, providerLDAP, configConfig)
	command := cli.New(renewer, logrLogger)
	return command, nil
}
